const fs=require('fs'),p=require('path');
const contentDir=p.join(__dirname,'..','content');
const L=[
['backend-apis','01-node-intro','Giới thiệu Node.js & npm','Node.js runtime và quản lý packages với npm','intermediate','javascript',
'# Giới thiệu Node.js & npm\n\nNode.js là runtime cho phép chạy JavaScript bên ngoài trình duyệt.\n\n## Cài đặt & Kiểm tra\n```bash\nnode --version\nnpm --version\n```\n\n## REPL\n```bash\nnode\n> 2 + 3\n5\n> console.log("Xin chào Node!")\n```\n\n## npm — Node Package Manager\n```bash\nnpm init -y              # Tạo package.json\nnpm install express      # Cài package\nnpm install -D nodemon   # Dev dependency\nnpm install -g typescript # Global\n```\n\n## package.json\n```json\n{\n  "name": "my-api",\n  "version": "1.0.0",\n  "scripts": {\n    "start": "node index.js",\n    "dev": "nodemon index.js"\n  },\n  "dependencies": {\n    "express": "^4.18.0"\n  }\n}\n```\n\n## Chạy file JS\n```javascript\n// index.js\nconsole.log("Hello from Node.js!");\nconsole.log("Platform:", process.platform);\nconsole.log("Node version:", process.version);\n```\n```bash\nnode index.js\n```'],

['backend-apis','02-node-modules','Modules & File System','Module system và thao tác file trong Node.js','intermediate','javascript',
'# Modules & File System\n\n## CommonJS Modules\n```javascript\n// math.js\nfunction add(a, b) { return a + b; }\nfunction multiply(a, b) { return a * b; }\nmodule.exports = { add, multiply };\n\n// main.js\nconst { add, multiply } = require("./math");\nconsole.log(add(2, 3)); // 5\n```\n\n## ES Modules\n```javascript\n// utils.mjs (hoặc "type": "module" trong package.json)\nexport const greet = (name) => `Xin chào, ${name}!`;\nexport default class Logger { /* ... */ }\n\n// app.mjs\nimport Logger, { greet } from "./utils.mjs";\n```\n\n## File System (fs)\n```javascript\nconst fs = require("fs");\nconst path = require("path");\n\n// Đọc file (async)\nfs.readFile("data.txt", "utf-8", (err, data) => {\n  if (err) throw err;\n  console.log(data);\n});\n\n// Đọc file (Promise)\nconst { readFile, writeFile } = require("fs/promises");\n\nasync function processFile() {\n  const content = await readFile("input.txt", "utf-8");\n  const result = content.toUpperCase();\n  await writeFile("output.txt", result);\n  console.log("Xong!");\n}\n\n// Path\nconst filePath = path.join(__dirname, "data", "config.json");\npath.extname("file.txt");  // ".txt"\npath.basename("/a/b/c.js"); // "c.js"\n```'],

['backend-apis','03-node-practice','Thực hành: Node.js CLI App','Bài tập tạo ứng dụng CLI với Node.js','intermediate','javascript',
'# Thực hành: Node.js CLI App\n\n```javascript\nconst fs = require("fs/promises");\nconst path = require("path");\n\nconst TASKS_FILE = path.join(__dirname, "tasks.json");\n\nasync function loadTasks() {\n  try {\n    const data = await fs.readFile(TASKS_FILE, "utf-8");\n    return JSON.parse(data);\n  } catch {\n    return [];\n  }\n}\n\nasync function saveTasks(tasks) {\n  await fs.writeFile(TASKS_FILE, JSON.stringify(tasks, null, 2));\n}\n\nasync function main() {\n  const [,, command, ...args] = process.argv;\n  const tasks = await loadTasks();\n\n  switch (command) {\n    case "add":\n      tasks.push({ text: args.join(" "), done: false, createdAt: new Date() });\n      await saveTasks(tasks);\n      console.log("✅ Đã thêm task!");\n      break;\n    case "list":\n      tasks.forEach((t, i) => {\n        const status = t.done ? "✅" : "⬜";\n        console.log(`${i + 1}. ${status} ${t.text}`);\n      });\n      break;\n    case "done":\n      const idx = parseInt(args[0]) - 1;\n      if (tasks[idx]) { tasks[idx].done = true; await saveTasks(tasks); }\n      console.log("✅ Đã hoàn thành!");\n      break;\n    default:\n      console.log("Cách dùng: node app.js [add|list|done] [args]");\n  }\n}\n\nmain();\n```\n\n## Chạy thử\n```bash\nnode app.js add Học Node.js\nnode app.js add Làm bài tập Express\nnode app.js list\nnode app.js done 1\n```'],

['backend-apis','04-express-routing','Routing & Middleware','Định tuyến và middleware trong Express.js','intermediate','javascript',
'# Express.js: Routing & Middleware\n\n## Setup\n```javascript\nconst express = require("express");\nconst app = express();\n\n// Middleware parsing JSON body\napp.use(express.json());\n\n// Logger middleware\napp.use((req, res, next) => {\n  console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);\n  next();\n});\n```\n\n## Routing\n```javascript\n// GET\napp.get("/api/users", (req, res) => {\n  res.json([{ id: 1, name: "An" }]);\n});\n\n// GET với params\napp.get("/api/users/:id", (req, res) => {\n  const { id } = req.params;\n  res.json({ id, name: "An" });\n});\n\n// POST\napp.post("/api/users", (req, res) => {\n  const { name, email } = req.body;\n  res.status(201).json({ id: Date.now(), name, email });\n});\n\n// PUT\napp.put("/api/users/:id", (req, res) => {\n  res.json({ message: "Updated", id: req.params.id });\n});\n\n// DELETE\napp.delete("/api/users/:id", (req, res) => {\n  res.status(204).send();\n});\n```\n\n## Router (modular)\n```javascript\n// routes/users.js\nconst router = express.Router();\nrouter.get("/", getUsers);\nrouter.post("/", createUser);\nmodule.exports = router;\n\n// app.js\napp.use("/api/users", require("./routes/users"));\n```\n\n## Khởi chạy\n```javascript\napp.listen(3000, () => console.log("Server đang chạy trên port 3000"));\n```'],

['backend-apis','05-express-req-res','Request, Response & Static Files','Xử lý request, response và phục vụ file tĩnh','intermediate','javascript',
'# Request, Response & Static Files\n\n## Request Object\n```javascript\napp.get("/api/search", (req, res) => {\n  // Query params: /api/search?q=nodejs&page=2\n  const { q, page = 1 } = req.query;\n\n  // Headers\n  const token = req.headers["authorization"];\n\n  // Cookies (cần cookie-parser)\n  const theme = req.cookies.theme;\n\n  res.json({ query: q, page, token });\n});\n\n// Body (POST/PUT)\napp.post("/api/upload", (req, res) => {\n  const { title, content } = req.body;\n  res.status(201).json({ title, content });\n});\n```\n\n## Response Object\n```javascript\n// JSON\nres.json({ status: "ok" });\n\n// Status code\nres.status(404).json({ error: "Không tìm thấy" });\nres.status(201).json({ message: "Đã tạo" });\n\n// Redirect\nres.redirect("/login");\n\n// Send file\nres.sendFile(path.join(__dirname, "public", "index.html"));\n```\n\n## Static Files\n```javascript\n// Phục vụ thư mục public/\napp.use(express.static("public"));\n\n// Với prefix\napp.use("/assets", express.static("public"));\n```\n\n## Error Handling\n```javascript\napp.use((err, req, res, next) => {\n  console.error(err.stack);\n  res.status(500).json({ error: "Lỗi server!" });\n});\n```'],

['backend-apis','06-express-practice','Thực hành: Express Server','Bài tập xây dựng REST API với Express','intermediate','javascript',
'# Thực hành: Express Server\n\n```javascript\nconst express = require("express");\nconst app = express();\napp.use(express.json());\n\nlet books = [\n  { id: 1, title: "Lập trình JavaScript", author: "An Nguyễn", year: 2024 },\n  { id: 2, title: "Node.js thực chiến", author: "Bình Trần", year: 2025 },\n];\nlet nextId = 3;\n\n// GET all\napp.get("/api/books", (req, res) => {\n  const { author, year } = req.query;\n  let result = books;\n  if (author) result = result.filter(b => b.author.includes(author));\n  if (year) result = result.filter(b => b.year === parseInt(year));\n  res.json(result);\n});\n\n// GET by ID\napp.get("/api/books/:id", (req, res) => {\n  const book = books.find(b => b.id === parseInt(req.params.id));\n  if (!book) return res.status(404).json({ error: "Không tìm thấy sách" });\n  res.json(book);\n});\n\n// POST\napp.post("/api/books", (req, res) => {\n  const { title, author, year } = req.body;\n  if (!title || !author) return res.status(400).json({ error: "Thiếu thông tin" });\n  const book = { id: nextId++, title, author, year: year || 2025 };\n  books.push(book);\n  res.status(201).json(book);\n});\n\n// PUT\napp.put("/api/books/:id", (req, res) => {\n  const book = books.find(b => b.id === parseInt(req.params.id));\n  if (!book) return res.status(404).json({ error: "Không tìm thấy" });\n  Object.assign(book, req.body);\n  res.json(book);\n});\n\n// DELETE\napp.delete("/api/books/:id", (req, res) => {\n  books = books.filter(b => b.id !== parseInt(req.params.id));\n  res.status(204).send();\n});\n\napp.listen(3000, () => console.log("API Books chạy tại http://localhost:3000"));\n```'],

['backend-apis','07-mongo-crud','NoSQL & MongoDB CRUD','Giới thiệu NoSQL và thao tác CRUD với MongoDB','intermediate','javascript',
'# NoSQL & MongoDB CRUD\n\n## SQL vs NoSQL\n| Tiêu chí | SQL | NoSQL (MongoDB) |\n|----------|-----|--------|\n| Cấu trúc | Bảng, hàng, cột | Collections, Documents |\n| Schema | Cố định | Linh hoạt |\n| Quan hệ | Foreign keys | Embedded / Reference |\n| Truy vấn | SQL | JSON-like queries |\n\n## MongoDB CRUD\n```javascript\nconst { MongoClient } = require("mongodb");\nconst uri = "mongodb://localhost:27017";\nconst client = new MongoClient(uri);\n\nasync function main() {\n  await client.connect();\n  const db = client.db("school");\n  const students = db.collection("students");\n\n  // CREATE\n  await students.insertOne({ name: "An", age: 20, scores: [9, 8, 7] });\n  await students.insertMany([\n    { name: "Bình", age: 21 },\n    { name: "Chi", age: 19 }\n  ]);\n\n  // READ\n  const all = await students.find({}).toArray();\n  const one = await students.findOne({ name: "An" });\n  const filtered = await students.find({ age: { $gte: 20 } }).toArray();\n\n  // UPDATE\n  await students.updateOne({ name: "An" }, { $set: { age: 21 } });\n  await students.updateMany({}, { $inc: { age: 1 } });\n\n  // DELETE\n  await students.deleteOne({ name: "Chi" });\n\n  await client.close();\n}\nmain();\n```\n\n## Query Operators\n```javascript\n{ age: { $gt: 18, $lt: 25 } }    // 18 < age < 25\n{ name: { $in: ["An", "Bình"] } } // name IN\n{ $or: [{ age: 20 }, { age: 21 }] }\n{ scores: { $elemMatch: { $gte: 9 } } }\n```'],

['backend-apis','08-mongoose-schema','Mongoose Schema & Models','Định nghĩa schema và models với Mongoose','intermediate','javascript',
'# Mongoose Schema & Models\n\n## Kết nối\n```javascript\nconst mongoose = require("mongoose");\nmongoose.connect("mongodb://localhost:27017/school");\n```\n\n## Schema & Model\n```javascript\nconst studentSchema = new mongoose.Schema({\n  name: { type: String, required: true, trim: true },\n  email: { type: String, required: true, unique: true, lowercase: true },\n  age: { type: Number, min: 0, max: 150 },\n  courses: [{ type: mongoose.Schema.Types.ObjectId, ref: "Course" }],\n  gpa: { type: Number, default: 0 },\n  isActive: { type: Boolean, default: true },\n  createdAt: { type: Date, default: Date.now },\n});\n\n// Instance methods\nstudentSchema.methods.getInfo = function() {\n  return `${this.name} - GPA: ${this.gpa}`;\n};\n\n// Static methods\nstudentSchema.statics.findByEmail = function(email) {\n  return this.findOne({ email });\n};\n\n// Virtual\nstudentSchema.virtual("isHonor").get(function() {\n  return this.gpa >= 3.5;\n});\n\nconst Student = mongoose.model("Student", studentSchema);\n```\n\n## CRUD Operations\n```javascript\n// Create\nconst student = await Student.create({ name: "An", email: "an@mail.com", age: 20 });\n\n// Read\nconst all = await Student.find({ isActive: true }).sort({ name: 1 }).limit(10);\nconst one = await Student.findById(id);\n\n// Update\nawait Student.findByIdAndUpdate(id, { gpa: 3.8 }, { new: true });\n\n// Delete\nawait Student.findByIdAndDelete(id);\n\n// Populate (JOIN)\nconst withCourses = await Student.findById(id).populate("courses");\n```'],

['backend-apis','09-mongo-practice','Thực hành: MongoDB API','Bài tập xây dựng API với Express + Mongoose','intermediate','javascript',
'# Thực hành: MongoDB API\n\n```javascript\nconst express = require("express");\nconst mongoose = require("mongoose");\n\nmongoose.connect("mongodb://localhost:27017/bookstore");\n\n// Schema\nconst bookSchema = new mongoose.Schema({\n  title: { type: String, required: true },\n  author: { type: String, required: true },\n  price: { type: Number, required: true, min: 0 },\n  category: { type: String, enum: ["fiction", "non-fiction", "tech"] },\n  inStock: { type: Boolean, default: true },\n}, { timestamps: true });\n\nconst Book = mongoose.model("Book", bookSchema);\n\nconst app = express();\napp.use(express.json());\n\n// CRUD Routes\napp.get("/api/books", async (req, res) => {\n  const { category, minPrice, maxPrice } = req.query;\n  const filter = {};\n  if (category) filter.category = category;\n  if (minPrice || maxPrice) {\n    filter.price = {};\n    if (minPrice) filter.price.$gte = Number(minPrice);\n    if (maxPrice) filter.price.$lte = Number(maxPrice);\n  }\n  const books = await Book.find(filter).sort({ createdAt: -1 });\n  res.json(books);\n});\n\napp.post("/api/books", async (req, res) => {\n  try {\n    const book = await Book.create(req.body);\n    res.status(201).json(book);\n  } catch (err) {\n    res.status(400).json({ error: err.message });\n  }\n});\n\napp.put("/api/books/:id", async (req, res) => {\n  const book = await Book.findByIdAndUpdate(req.params.id, req.body, { new: true });\n  if (!book) return res.status(404).json({ error: "Không tìm thấy" });\n  res.json(book);\n});\n\napp.delete("/api/books/:id", async (req, res) => {\n  await Book.findByIdAndDelete(req.params.id);\n  res.status(204).send();\n});\n\napp.listen(3000);\n```'],

['backend-apis','10-api-design','RESTful API Design','Nguyên tắc thiết kế RESTful API','intermediate','javascript',
'# RESTful API Design\n\n## Nguyên tắc REST\n\n### 1. URL = Resource (danh từ, số nhiều)\n```\n✅ GET    /api/users          Lấy danh sách\n✅ GET    /api/users/123       Lấy chi tiết\n✅ POST   /api/users           Tạo mới\n✅ PUT    /api/users/123       Cập nhật toàn bộ\n✅ PATCH  /api/users/123       Cập nhật một phần\n✅ DELETE /api/users/123       Xóa\n\n❌ GET /api/getUsers\n❌ POST /api/createUser\n❌ GET /api/user/delete/123\n```\n\n### 2. HTTP Status Codes\n| Code | Ý nghĩa |\n|------|--------|\n| 200 | Thành công |\n| 201 | Đã tạo (POST) |\n| 204 | Thành công, không có body (DELETE) |\n| 400 | Bad Request — dữ liệu không hợp lệ |\n| 401 | Unauthorized — chưa đăng nhập |\n| 403 | Forbidden — không có quyền |\n| 404 | Not Found |\n| 500 | Server Error |\n\n### 3. Response Format\n```json\n{\n  "data": [{ "id": 1, "name": "An" }],\n  "meta": { "total": 50, "page": 1, "limit": 10 },\n  "error": null\n}\n```\n\n### 4. Pagination & Filtering\n```\nGET /api/users?page=2&limit=10&sort=-createdAt\nGET /api/users?role=admin&search=an\n```\n\n### 5. Versioning\n```\n/api/v1/users\n/api/v2/users\n```'],

['backend-apis','11-api-auth','Authentication & Security','Xác thực người dùng và bảo mật API','intermediate','javascript',
'# Authentication & Security\n\n## JWT (JSON Web Token)\n```javascript\nconst jwt = require("jsonwebtoken");\nconst SECRET = process.env.JWT_SECRET || "my-secret-key";\n\n// Tạo token\nfunction generateToken(user) {\n  return jwt.sign(\n    { id: user.id, email: user.email, role: user.role },\n    SECRET,\n    { expiresIn: "7d" }\n  );\n}\n\n// Middleware xác thực\nfunction authenticate(req, res, next) {\n  const token = req.headers.authorization?.split(" ")[1];\n  if (!token) return res.status(401).json({ error: "Token không tồn tại" });\n  try {\n    req.user = jwt.verify(token, SECRET);\n    next();\n  } catch {\n    res.status(401).json({ error: "Token không hợp lệ" });\n  }\n}\n\n// Middleware phân quyền\nfunction authorize(...roles) {\n  return (req, res, next) => {\n    if (!roles.includes(req.user.role)) {\n      return res.status(403).json({ error: "Không có quyền" });\n    }\n    next();\n  };\n}\n```\n\n## Đăng ký & Đăng nhập\n```javascript\nconst bcrypt = require("bcrypt");\n\napp.post("/api/register", async (req, res) => {\n  const hashedPassword = await bcrypt.hash(req.body.password, 10);\n  const user = await User.create({ ...req.body, password: hashedPassword });\n  const token = generateToken(user);\n  res.status(201).json({ user, token });\n});\n\napp.post("/api/login", async (req, res) => {\n  const user = await User.findOne({ email: req.body.email });\n  if (!user || !(await bcrypt.compare(req.body.password, user.password))) {\n    return res.status(401).json({ error: "Sai email hoặc mật khẩu" });\n  }\n  res.json({ token: generateToken(user) });\n});\n```\n\n## Bảo mật cơ bản\n```javascript\nconst helmet = require("helmet");\nconst rateLimit = require("express-rate-limit");\nconst cors = require("cors");\n\napp.use(helmet());          // Security headers\napp.use(cors());            // CORS\napp.use(rateLimit({ windowMs: 15*60*1000, max: 100 }));\n```'],

['backend-apis','12-api-practice','Thực hành: Full API Project','Bài tập xây dựng API hoàn chỉnh','intermediate','javascript',
'# Thực hành: Full API Project\n\n## Cấu trúc dự án\n```\nmy-api/\n├── src/\n│   ├── models/\n│   │   ├── User.js\n│   │   └── Course.js\n│   ├── routes/\n│   │   ├── auth.js\n│   │   └── courses.js\n│   ├── middleware/\n│   │   └── auth.js\n│   └── app.js\n├── .env\n└── package.json\n```\n\n## .env\n```\nPORT=3000\nMONGO_URI=mongodb://localhost:27017/codemastery\nJWT_SECRET=your-secret-key-here\n```\n\n## app.js\n```javascript\nrequire("dotenv").config();\nconst express = require("express");\nconst mongoose = require("mongoose");\nconst cors = require("cors");\n\nconst app = express();\napp.use(cors());\napp.use(express.json());\n\n// Routes\napp.use("/api/auth", require("./routes/auth"));\napp.use("/api/courses", require("./routes/courses"));\n\n// Error handler\napp.use((err, req, res, next) => {\n  console.error(err);\n  res.status(err.status || 500).json({ error: err.message });\n});\n\nmongoose.connect(process.env.MONGO_URI)\n  .then(() => {\n    app.listen(process.env.PORT, () =>\n      console.log("API chạy tại port " + process.env.PORT)\n    );\n  });\n```\n\n## Thử thách\n1. Thêm pagination cho GET /api/courses\n2. Thêm validation với Joi hoặc express-validator\n3. Viết unit tests với Jest\n4. Deploy lên Railway hoặc Render'],
];

let c=0;
for(const[folder,file,title,desc,diff,lang,body]of L){
  const dir=p.join(contentDir,folder);
  if(!fs.existsSync(dir))fs.mkdirSync(dir,{recursive:true});
  fs.writeFileSync(p.join(dir,file+'.mdx'),'---\ntitle: "'+title+'"\ndescription: "'+desc+'"\ndifficulty: "'+diff+'"\nlanguage: "'+lang+'"\n---\n\n'+body+'\n');
  c++;
}
console.log('Done! Created '+c+' MDX files (Backend & APIs) in '+contentDir);
